// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'db_model.dart';

// **************************************************************************
// SqfEntityGenerator
// **************************************************************************

// ignore_for_file: non_constant_identifier_names

//  These classes was generated by SqfEntity
//  Copyright (c) 2019, All rights reserved. Use of this source code is governed by a
//  Apache license that can be found in the LICENSE file.

//  To use these SqfEntity classes do following:
//  - import model.dart into where to use
//  - start typing ex:SubCategoryDBModel.select()... (add a few filters with fluent methods)...(add orderBy/orderBydesc if you want)...
//  - and then just put end of filters / or end of only select()  toSingle() / or toList()
//  - you can select one or return List<yourObject> by your filters and orders
//  - also you can batch update or batch delete by using delete/update methods instead of tosingle/tolist methods
//    Enjoy.. Huseyin Tokpunar

// BEGIN TABLES
// SubCategoryDBModel TABLE
class TableSubCategoryDBModel extends SqfEntityTableBase {
  TableSubCategoryDBModel() {
    // declare properties of EntityTable
    tableName = 'subcategories';
    primaryKeyName = 'id';
    primaryKeyType = PrimaryKeyType.integer_auto_incremental;
    useSoftDeleting = true;
    // when useSoftDeleting is true, creates a field named 'isDeleted' on the table, and set to '1' this field when item deleted (does not hard delete)

    // declare fields
    fields = [
      SqfEntityFieldBase('name', DbType.text),
      SqfEntityFieldBase('main_category_id', DbType.integer),
    ];
    super.init();
  }
  static SqfEntityTableBase? _instance;
  static SqfEntityTableBase get getInstance {
    return _instance = _instance ?? TableSubCategoryDBModel();
  }
}
// END TABLES

// BEGIN SEQUENCES
// identity SEQUENCE
class SequenceIdentitySequence extends SqfEntitySequenceBase {
  SequenceIdentitySequence() {
    sequenceName = 'identity';
    maxValue =
        9007199254740991; /* optional. default is max int (9.223.372.036.854.775.807) */
    cycle = false; /* optional. default is false; */
    minValue = 0; /* optional. default is 0 */
    incrementBy = 1; /* optional. default is 1 */
    startWith = 0; /* optional. default is 0 */
    super.init();
  }
  static SequenceIdentitySequence? _instance;
  static SequenceIdentitySequence get getInstance {
    return _instance = _instance ?? SequenceIdentitySequence();
  }
}
// END SEQUENCES

// BEGIN DATABASE MODEL
class ExpensesDBModel extends SqfEntityModelProvider {
  ExpensesDBModel() {
    databaseName = expensesDBModel.databaseName;
    password = expensesDBModel.password;
    dbVersion = expensesDBModel.dbVersion;
    preSaveAction = expensesDBModel.preSaveAction;
    logFunction = expensesDBModel.logFunction;
    databaseTables = [
      TableSubCategoryDBModel.getInstance,
    ];

    sequences = [
      SequenceIdentitySequence.getInstance,
    ];

    bundledDatabasePath = expensesDBModel
        .bundledDatabasePath; //'assets/sample.db'; // This value is optional. When bundledDatabasePath is empty then EntityBase creats a new database when initializing the database
    databasePath = expensesDBModel.databasePath;
  }
  Map<String, dynamic> getControllers() {
    final controllers = <String, dynamic>{};

    return controllers;
  }
}
// END DATABASE MODEL

// BEGIN ENTITIES
// region SubCategoryDBModel
class SubCategoryDBModel extends TableBase {
  SubCategoryDBModel(
      {this.id, this.name, this.main_category_id, this.isDeleted}) {
    _setDefaultValues();
    softDeleteActivated = true;
  }
  SubCategoryDBModel.withFields(
      this.name, this.main_category_id, this.isDeleted) {
    _setDefaultValues();
  }
  SubCategoryDBModel.withId(
      this.id, this.name, this.main_category_id, this.isDeleted) {
    _setDefaultValues();
  }
  // fromMap v2.0
  SubCategoryDBModel.fromMap(Map<String, dynamic> o,
      {bool setDefaultValues = true}) {
    if (setDefaultValues) {
      _setDefaultValues();
    }
    id = int.tryParse(o['id'].toString());
    if (o['name'] != null) {
      name = o['name'].toString();
    }
    if (o['main_category_id'] != null) {
      main_category_id = int.tryParse(o['main_category_id'].toString());
    }
    isDeleted = o['isDeleted'] != null
        ? o['isDeleted'] == 1 || o['isDeleted'] == true
        : null;
  }
  // FIELDS (SubCategoryDBModel)
  int? id;
  String? name;
  int? main_category_id;
  bool? isDeleted;

  // end FIELDS (SubCategoryDBModel)

  static const bool _softDeleteActivated = true;
  SubCategoryDBModelManager? __mnSubCategoryDBModel;

  SubCategoryDBModelManager get _mnSubCategoryDBModel {
    return __mnSubCategoryDBModel =
        __mnSubCategoryDBModel ?? SubCategoryDBModelManager();
  }

  // METHODS
  @override
  Map<String, dynamic> toMap(
      {bool forQuery = false, bool forJson = false, bool forView = false}) {
    final map = <String, dynamic>{};
    map['id'] = id;
    if (name != null || !forView) {
      map['name'] = name;
    }
    if (main_category_id != null || !forView) {
      map['main_category_id'] = main_category_id;
    }
    if (isDeleted != null) {
      map['isDeleted'] = forQuery ? (isDeleted! ? 1 : 0) : isDeleted;
    }

    return map;
  }

  @override
  Future<Map<String, dynamic>> toMapWithChildren(
      [bool forQuery = false,
      bool forJson = false,
      bool forView = false]) async {
    final map = <String, dynamic>{};
    map['id'] = id;
    if (name != null || !forView) {
      map['name'] = name;
    }
    if (main_category_id != null || !forView) {
      map['main_category_id'] = main_category_id;
    }
    if (isDeleted != null) {
      map['isDeleted'] = forQuery ? (isDeleted! ? 1 : 0) : isDeleted;
    }

    return map;
  }

  /// This method returns Json String [SubCategoryDBModel]
  @override
  String toJson() {
    return json.encode(toMap(forJson: true));
  }

  /// This method returns Json String [SubCategoryDBModel]
  @override
  Future<String> toJsonWithChilds() async {
    return json.encode(await toMapWithChildren(false, true));
  }

  @override
  List<dynamic> toArgs() {
    return [name, main_category_id, isDeleted];
  }

  @override
  List<dynamic> toArgsWithIds() {
    return [id, name, main_category_id, isDeleted];
  }

  static Future<List<SubCategoryDBModel>> fromJson(String jsonBody) async {
    final Iterable list = await json.decode(jsonBody) as Iterable;
    var objList = <SubCategoryDBModel>[];
    try {
      objList = list
          .map((subcategorydbmodel) => SubCategoryDBModel.fromMap(
              subcategorydbmodel as Map<String, dynamic>))
          .toList();
    } catch (e) {
      debugPrint(
          'SQFENTITY ERROR SubCategoryDBModel.fromJson: ErrorMessage: ${e.toString()}');
    }
    return objList;
  }

  static Future<List<SubCategoryDBModel>> fromMapList(List<dynamic> data,
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields,
      bool setDefaultValues = true}) async {
    final List<SubCategoryDBModel> objList = <SubCategoryDBModel>[];
    loadedFields = loadedFields ?? [];
    for (final map in data) {
      final obj = SubCategoryDBModel.fromMap(map as Map<String, dynamic>,
          setDefaultValues: setDefaultValues);

      objList.add(obj);
    }
    return objList;
  }

  /// returns SubCategoryDBModel by ID if exist, otherwise returns null
  /// Primary Keys: int? id
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  /// ex: getById(preload:true) -> Loads all related objects
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  /// ex: getById(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  /// <returns>returns [SubCategoryDBModel] if exist, otherwise returns null
  Future<SubCategoryDBModel?> getById(int? id,
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields}) async {
    if (id == null) {
      return null;
    }
    SubCategoryDBModel? obj;
    final data = await _mnSubCategoryDBModel.getById([id]);
    if (data.length != 0) {
      obj = SubCategoryDBModel.fromMap(data[0] as Map<String, dynamic>);
    } else {
      obj = null;
    }
    return obj;
  }

  /// Saves the (SubCategoryDBModel) object. If the id field is null, saves as a new record and returns new id, if id is not null then updates record
  /// ignoreBatch = true as a default. Set ignoreBatch to false if you run more than one save() operation those are between batchStart and batchCommit
  /// <returns>Returns id
  @override
  Future<int?> save({bool ignoreBatch = true}) async {
    if (id == null || id == 0) {
      id = await _mnSubCategoryDBModel.insert(this, ignoreBatch);
    } else {
      await _mnSubCategoryDBModel.update(this);
    }

    return id;
  }

  /// Saves the (SubCategoryDBModel) object. If the id field is null, saves as a new record and returns new id, if id is not null then updates record
  /// ignoreBatch = true as a default. Set ignoreBatch to false if you run more than one save() operation those are between batchStart and batchCommit
  /// <returns>Returns id
  @override
  Future<int?> saveOrThrow({bool ignoreBatch = true}) async {
    if (id == null || id == 0) {
      id = await _mnSubCategoryDBModel.insertOrThrow(this, ignoreBatch);

      isInsert = true;
    } else {
      // id= await _upsert(); // removed in sqfentity_gen 1.3.0+6
      await _mnSubCategoryDBModel.updateOrThrow(this);
    }

    return id;
  }

  /// saveAs SubCategoryDBModel. Returns a new Primary Key value of SubCategoryDBModel

  /// <returns>Returns a new Primary Key value of SubCategoryDBModel
  @override
  Future<int?> saveAs({bool ignoreBatch = true}) async {
    id = null;

    return save(ignoreBatch: ignoreBatch);
  }

  /// saveAll method saves the sent List<SubCategoryDBModel> as a bulk in one transaction
  /// Returns a <List<BoolResult>>
  static Future<List<dynamic>> saveAll(
      List<SubCategoryDBModel> subcategorydbmodels,
      {bool? exclusive,
      bool? noResult,
      bool? continueOnError}) async {
    List<dynamic>? result = [];
    // If there is no open transaction, start one
    final isStartedBatch = await ExpensesDBModel().batchStart();
    for (final obj in subcategorydbmodels) {
      await obj.save(ignoreBatch: false);
    }
    if (!isStartedBatch) {
      result = await ExpensesDBModel().batchCommit(
          exclusive: exclusive,
          noResult: noResult,
          continueOnError: continueOnError);
      for (int i = 0; i < subcategorydbmodels.length; i++) {
        if (subcategorydbmodels[i].id == null) {
          subcategorydbmodels[i].id = result![i] as int;
        }
      }
    }
    return result!;
  }

  /// Updates if the record exists, otherwise adds a new row
  /// <returns>Returns id
  @override
  Future<int?> upsert({bool ignoreBatch = true}) async {
    try {
      final result = await _mnSubCategoryDBModel.rawInsert(
          'INSERT OR REPLACE INTO subcategories (id, name, main_category_id,isDeleted)  VALUES (?,?,?,?)',
          [id, name, main_category_id, isDeleted],
          ignoreBatch);
      if (result! > 0) {
        saveResult = BoolResult(
            success: true,
            successMessage: 'SubCategoryDBModel id=$id updated successfully');
      } else {
        saveResult = BoolResult(
            success: false,
            errorMessage: 'SubCategoryDBModel id=$id did not update');
      }
      return id;
    } catch (e) {
      saveResult = BoolResult(
          success: false,
          errorMessage:
              'SubCategoryDBModel Save failed. Error: ${e.toString()}');
      return null;
    }
  }

  /// inserts or replaces the sent List<<SubCategoryDBModel>> as a bulk in one transaction.
  /// upsertAll() method is faster then saveAll() method. upsertAll() should be used when you are sure that the primary key is greater than zero
  /// Returns a BoolCommitResult
  @override
  Future<BoolCommitResult> upsertAll(
      List<SubCategoryDBModel> subcategorydbmodels,
      {bool? exclusive,
      bool? noResult,
      bool? continueOnError}) async {
    final results = await _mnSubCategoryDBModel.rawInsertAll(
        'INSERT OR REPLACE INTO subcategories (id, name, main_category_id,isDeleted)  VALUES (?,?,?,?)',
        subcategorydbmodels,
        exclusive: exclusive,
        noResult: noResult,
        continueOnError: continueOnError);
    return results;
  }

  /// Deletes SubCategoryDBModel

  /// <returns>BoolResult res.success= true (Deleted), false (Could not be deleted)
  @override
  Future<BoolResult> delete([bool hardDelete = false]) async {
    debugPrint('SQFENTITIY: delete SubCategoryDBModel invoked (id=$id)');
    if (!_softDeleteActivated || hardDelete || isDeleted!) {
      return _mnSubCategoryDBModel
          .delete(QueryParams(whereString: 'id=?', whereArguments: [id]));
    } else {
      return _mnSubCategoryDBModel.updateBatch(
          QueryParams(whereString: 'id=?', whereArguments: [id]),
          {'isDeleted': 1});
    }
  }

  /// Recover SubCategoryDBModel

  /// <returns>BoolResult res.success=Recovered, not res.success=Can not recovered
  @override
  Future<BoolResult> recover([bool recoverChilds = true]) async {
    debugPrint('SQFENTITIY: recover SubCategoryDBModel invoked (id=$id)');
    {
      return _mnSubCategoryDBModel.updateBatch(
          QueryParams(whereString: 'id=?', whereArguments: [id]),
          {'isDeleted': 0});
    }
  }

  @override
  SubCategoryDBModelFilterBuilder select(
      {List<String>? columnsToSelect, bool? getIsDeleted}) {
    return SubCategoryDBModelFilterBuilder(this, getIsDeleted)
      ..qparams.selectColumns = columnsToSelect;
  }

  @override
  SubCategoryDBModelFilterBuilder distinct(
      {List<String>? columnsToSelect, bool? getIsDeleted}) {
    return SubCategoryDBModelFilterBuilder(this, getIsDeleted)
      ..qparams.selectColumns = columnsToSelect
      ..qparams.distinct = true;
  }

  void _setDefaultValues() {
    isDeleted = isDeleted ?? false;
  }

  @override
  void rollbackPk() {
    if (isInsert == true) {
      id = null;
    }
  }

  // END METHODS
  // BEGIN CUSTOM CODE
  /*
      you can define customCode property of your SqfEntityTable constant. For example:
      const tablePerson = SqfEntityTable(
      tableName: 'person',
      primaryKeyName: 'id',
      primaryKeyType: PrimaryKeyType.integer_auto_incremental,
      fields: [
        SqfEntityField('firstName', DbType.text),
        SqfEntityField('lastName', DbType.text),
      ],
      customCode: '''
       String fullName()
       { 
         return '$firstName $lastName';
       }
      ''');
     */
  // END CUSTOM CODE
}
// endregion subcategorydbmodel

// region SubCategoryDBModelField
class SubCategoryDBModelField extends FilterBase {
  SubCategoryDBModelField(SubCategoryDBModelFilterBuilder subcategorydbmodelFB)
      : super(subcategorydbmodelFB);

  @override
  SubCategoryDBModelFilterBuilder equals(dynamic pValue) {
    return super.equals(pValue) as SubCategoryDBModelFilterBuilder;
  }

  @override
  SubCategoryDBModelFilterBuilder equalsOrNull(dynamic pValue) {
    return super.equalsOrNull(pValue) as SubCategoryDBModelFilterBuilder;
  }

  @override
  SubCategoryDBModelFilterBuilder isNull() {
    return super.isNull() as SubCategoryDBModelFilterBuilder;
  }

  @override
  SubCategoryDBModelFilterBuilder contains(dynamic pValue) {
    return super.contains(pValue) as SubCategoryDBModelFilterBuilder;
  }

  @override
  SubCategoryDBModelFilterBuilder startsWith(dynamic pValue) {
    return super.startsWith(pValue) as SubCategoryDBModelFilterBuilder;
  }

  @override
  SubCategoryDBModelFilterBuilder endsWith(dynamic pValue) {
    return super.endsWith(pValue) as SubCategoryDBModelFilterBuilder;
  }

  @override
  SubCategoryDBModelFilterBuilder between(dynamic pFirst, dynamic pLast) {
    return super.between(pFirst, pLast) as SubCategoryDBModelFilterBuilder;
  }

  @override
  SubCategoryDBModelFilterBuilder greaterThan(dynamic pValue) {
    return super.greaterThan(pValue) as SubCategoryDBModelFilterBuilder;
  }

  @override
  SubCategoryDBModelFilterBuilder lessThan(dynamic pValue) {
    return super.lessThan(pValue) as SubCategoryDBModelFilterBuilder;
  }

  @override
  SubCategoryDBModelFilterBuilder greaterThanOrEquals(dynamic pValue) {
    return super.greaterThanOrEquals(pValue) as SubCategoryDBModelFilterBuilder;
  }

  @override
  SubCategoryDBModelFilterBuilder lessThanOrEquals(dynamic pValue) {
    return super.lessThanOrEquals(pValue) as SubCategoryDBModelFilterBuilder;
  }

  @override
  SubCategoryDBModelFilterBuilder inValues(dynamic pValue) {
    return super.inValues(pValue) as SubCategoryDBModelFilterBuilder;
  }

  @override
  SubCategoryDBModelField get not {
    return super.not as SubCategoryDBModelField;
  }
}
// endregion SubCategoryDBModelField

// region SubCategoryDBModelFilterBuilder
class SubCategoryDBModelFilterBuilder extends ConjunctionBase {
  SubCategoryDBModelFilterBuilder(SubCategoryDBModel obj, bool? getIsDeleted)
      : super(obj, getIsDeleted) {
    _mnSubCategoryDBModel = obj._mnSubCategoryDBModel;
    _softDeleteActivated = obj.softDeleteActivated;
  }

  bool _softDeleteActivated = false;
  SubCategoryDBModelManager? _mnSubCategoryDBModel;

  /// put the sql keyword 'AND'
  @override
  SubCategoryDBModelFilterBuilder get and {
    super.and;
    return this;
  }

  /// put the sql keyword 'OR'
  @override
  SubCategoryDBModelFilterBuilder get or {
    super.or;
    return this;
  }

  /// open parentheses
  @override
  SubCategoryDBModelFilterBuilder get startBlock {
    super.startBlock;
    return this;
  }

  /// String whereCriteria, write raw query without 'where' keyword. Like this: 'field1 like 'test%' and field2 = 3'
  @override
  SubCategoryDBModelFilterBuilder where(String? whereCriteria,
      {dynamic parameterValue}) {
    super.where(whereCriteria, parameterValue: parameterValue);
    return this;
  }

  /// page = page number,
  /// pagesize = row(s) per page
  @override
  SubCategoryDBModelFilterBuilder page(int page, int pagesize) {
    super.page(page, pagesize);
    return this;
  }

  /// int count = LIMIT
  @override
  SubCategoryDBModelFilterBuilder top(int count) {
    super.top(count);
    return this;
  }

  /// close parentheses
  @override
  SubCategoryDBModelFilterBuilder get endBlock {
    super.endBlock;
    return this;
  }

  /// argFields might be String or List<String>.
  /// Example 1: argFields='name, date'
  /// Example 2: argFields = ['name', 'date']
  @override
  SubCategoryDBModelFilterBuilder orderBy(dynamic argFields) {
    super.orderBy(argFields);
    return this;
  }

  /// argFields might be String or List<String>.
  /// Example 1: argFields='field1, field2'
  /// Example 2: argFields = ['field1', 'field2']
  @override
  SubCategoryDBModelFilterBuilder orderByDesc(dynamic argFields) {
    super.orderByDesc(argFields);
    return this;
  }

  /// argFields might be String or List<String>.
  /// Example 1: argFields='field1, field2'
  /// Example 2: argFields = ['field1', 'field2']
  @override
  SubCategoryDBModelFilterBuilder groupBy(dynamic argFields) {
    super.groupBy(argFields);
    return this;
  }

  /// argFields might be String or List<String>.
  /// Example 1: argFields='name, date'
  /// Example 2: argFields = ['name', 'date']
  @override
  SubCategoryDBModelFilterBuilder having(dynamic argFields) {
    super.having(argFields);
    return this;
  }

  SubCategoryDBModelField _setField(
      SubCategoryDBModelField? field, String colName, DbType dbtype) {
    return SubCategoryDBModelField(this)
      ..param = DbParameter(
          dbType: dbtype, columnName: colName, wStartBlock: openedBlock);
  }

  SubCategoryDBModelField? _id;
  SubCategoryDBModelField get id {
    return _id = _setField(_id, 'id', DbType.integer);
  }

  SubCategoryDBModelField? _name;
  SubCategoryDBModelField get name {
    return _name = _setField(_name, 'name', DbType.text);
  }

  SubCategoryDBModelField? _main_category_id;
  SubCategoryDBModelField get main_category_id {
    return _main_category_id =
        _setField(_main_category_id, 'main_category_id', DbType.integer);
  }

  SubCategoryDBModelField? _isDeleted;
  SubCategoryDBModelField get isDeleted {
    return _isDeleted = _setField(_isDeleted, 'isDeleted', DbType.bool);
  }

  /// Deletes List<SubCategoryDBModel> bulk by query
  ///
  /// <returns>BoolResult res.success= true (Deleted), false (Could not be deleted)
  @override
  Future<BoolResult> delete([bool hardDelete = false]) async {
    buildParameters();
    var r = BoolResult(success: false);

    if (_softDeleteActivated && !hardDelete) {
      r = await _mnSubCategoryDBModel!.updateBatch(qparams, {'isDeleted': 1});
    } else {
      r = await _mnSubCategoryDBModel!.delete(qparams);
    }
    return r;
  }

  /// Recover List<SubCategoryDBModel> bulk by query
  @override
  Future<BoolResult> recover() async {
    buildParameters(getIsDeleted: true);
    debugPrint('SQFENTITIY: recover SubCategoryDBModel bulk invoked');
    return _mnSubCategoryDBModel!.updateBatch(qparams, {'isDeleted': 0});
  }

  /// using:
  /// update({'fieldName': Value})
  /// fieldName must be String. Value is dynamic, it can be any of the (int, bool, String.. )
  @override
  Future<BoolResult> update(Map<String, dynamic> values) {
    buildParameters();
    if (qparams.limit! > 0 || qparams.offset! > 0) {
      qparams.whereString =
          'id IN (SELECT id from subcategories ${qparams.whereString!.isNotEmpty ? 'WHERE ${qparams.whereString}' : ''}${qparams.limit! > 0 ? ' LIMIT ${qparams.limit}' : ''}${qparams.offset! > 0 ? ' OFFSET ${qparams.offset}' : ''})';
    }
    return _mnSubCategoryDBModel!.updateBatch(qparams, values);
  }

  /// This method always returns [SubCategoryDBModel] Obj if exist, otherwise returns null
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  /// ex: toSingle(preload:true) -> Loads all related objects
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  /// ex: toSingle(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  /// <returns> SubCategoryDBModel?
  @override
  Future<SubCategoryDBModel?> toSingle(
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields}) async {
    buildParameters(pSize: 1);
    final objFuture = _mnSubCategoryDBModel!.toList(qparams);
    final data = await objFuture;
    SubCategoryDBModel? obj;
    if (data.isNotEmpty) {
      obj = SubCategoryDBModel.fromMap(data[0] as Map<String, dynamic>);
    } else {
      obj = null;
    }
    return obj;
  }

  /// This method always returns [SubCategoryDBModel]
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  /// ex: toSingle(preload:true) -> Loads all related objects
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  /// ex: toSingle(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  /// <returns> SubCategoryDBModel?
  @override
  Future<SubCategoryDBModel> toSingleOrDefault(
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields}) async {
    return await toSingle(
            preload: preload,
            preloadFields: preloadFields,
            loadParents: loadParents,
            loadedFields: loadedFields) ??
        SubCategoryDBModel();
  }

  /// This method returns int. [SubCategoryDBModel]
  /// <returns>int
  @override
  Future<int> toCount(
      [VoidCallback Function(int c)? subcategorydbmodelCount]) async {
    buildParameters();
    qparams.selectColumns = ['COUNT(1) AS CNT'];
    final subcategorydbmodelsFuture =
        await _mnSubCategoryDBModel!.toList(qparams);
    final int count = subcategorydbmodelsFuture[0]['CNT'] as int;
    if (subcategorydbmodelCount != null) {
      subcategorydbmodelCount(count);
    }
    return count;
  }

  /// This method returns List<SubCategoryDBModel> [SubCategoryDBModel]
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  /// ex: toList(preload:true) -> Loads all related objects
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  /// ex: toList(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  /// <returns>List<SubCategoryDBModel>
  @override
  Future<List<SubCategoryDBModel>> toList(
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields}) async {
    final data = await toMapList();
    final List<SubCategoryDBModel> subcategorydbmodelsData =
        await SubCategoryDBModel.fromMapList(data,
            preload: preload,
            preloadFields: preloadFields,
            loadParents: loadParents,
            loadedFields: loadedFields,
            setDefaultValues: qparams.selectColumns == null);
    return subcategorydbmodelsData;
  }

  /// This method returns Json String [SubCategoryDBModel]
  @override
  Future<String> toJson() async {
    final list = <dynamic>[];
    final data = await toList();
    for (var o in data) {
      list.add(o.toMap(forJson: true));
    }
    return json.encode(list);
  }

  /// This method returns Json String. [SubCategoryDBModel]
  @override
  Future<String> toJsonWithChilds() async {
    final list = <dynamic>[];
    final data = await toList();
    for (var o in data) {
      list.add(await o.toMapWithChildren(false, true));
    }
    return json.encode(list);
  }

  /// This method returns List<dynamic>. [SubCategoryDBModel]
  /// <returns>List<dynamic>
  @override
  Future<List<dynamic>> toMapList() async {
    buildParameters();
    return await _mnSubCategoryDBModel!.toList(qparams);
  }

  /// This method returns Primary Key List SQL and Parameters retVal = Map<String,dynamic>. [SubCategoryDBModel]
  /// retVal['sql'] = SQL statement string, retVal['args'] = whereArguments List<dynamic>;
  /// <returns>List<String>
  @override
  Map<String, dynamic> toListPrimaryKeySQL([bool buildParams = true]) {
    final Map<String, dynamic> retVal = <String, dynamic>{};
    if (buildParams) {
      buildParameters();
    }
    retVal['sql'] =
        'SELECT `id` FROM subcategories WHERE ${qparams.whereString}';
    retVal['args'] = qparams.whereArguments;
    return retVal;
  }

  /// This method returns Primary Key List<int>.
  /// <returns>List<int>
  @override
  Future<List<int>> toListPrimaryKey([bool buildParams = true]) async {
    if (buildParams) {
      buildParameters();
    }
    final List<int> idData = <int>[];
    qparams.selectColumns = ['id'];
    final idFuture = await _mnSubCategoryDBModel!.toList(qparams);

    final int count = idFuture.length;
    for (int i = 0; i < count; i++) {
      idData.add(idFuture[i]['id'] as int);
    }
    return idData;
  }

  /// Returns List<dynamic> for selected columns. Use this method for 'groupBy' with min,max,avg..  [SubCategoryDBModel]
  /// Sample usage: (see EXAMPLE 4.2 at https://github.com/hhtokpinar/sqfEntity#group-by)
  @override
  Future<List<dynamic>> toListObject() async {
    buildParameters();

    final objectFuture = _mnSubCategoryDBModel!.toList(qparams);

    final List<dynamic> objectsData = <dynamic>[];
    final data = await objectFuture;
    final int count = data.length;
    for (int i = 0; i < count; i++) {
      objectsData.add(data[i]);
    }
    return objectsData;
  }

  /// Returns List<String> for selected first column
  /// Sample usage: await SubCategoryDBModel.select(columnsToSelect: ['columnName']).toListString()
  @override
  Future<List<String>> toListString(
      [VoidCallback Function(List<String> o)? listString]) async {
    buildParameters();

    final objectFuture = _mnSubCategoryDBModel!.toList(qparams);

    final List<String> objectsData = <String>[];
    final data = await objectFuture;
    final int count = data.length;
    for (int i = 0; i < count; i++) {
      objectsData.add(data[i][qparams.selectColumns![0]].toString());
    }
    if (listString != null) {
      listString(objectsData);
    }
    return objectsData;
  }
}
// endregion SubCategoryDBModelFilterBuilder

// region SubCategoryDBModelFields
class SubCategoryDBModelFields {
  static TableField? _fId;
  static TableField get id {
    return _fId = _fId ?? SqlSyntax.setField(_fId, 'id', DbType.integer);
  }

  static TableField? _fName;
  static TableField get name {
    return _fName = _fName ?? SqlSyntax.setField(_fName, 'name', DbType.text);
  }

  static TableField? _fMain_category_id;
  static TableField get main_category_id {
    return _fMain_category_id = _fMain_category_id ??
        SqlSyntax.setField(
            _fMain_category_id, 'main_category_id', DbType.integer);
  }

  static TableField? _fIsDeleted;
  static TableField get isDeleted {
    return _fIsDeleted = _fIsDeleted ??
        SqlSyntax.setField(_fIsDeleted, 'isDeleted', DbType.integer);
  }
}
// endregion SubCategoryDBModelFields

//region SubCategoryDBModelManager
class SubCategoryDBModelManager extends SqfEntityProvider {
  SubCategoryDBModelManager()
      : super(ExpensesDBModel(),
            tableName: _tableName,
            primaryKeyList: _primaryKeyList,
            whereStr: _whereStr);
  static const String _tableName = 'subcategories';
  static const List<String> _primaryKeyList = ['id'];
  static const String _whereStr = 'id=?';
}

//endregion SubCategoryDBModelManager
/// Region SEQUENCE IdentitySequence
class IdentitySequence {
  /// Assigns a new value when it is triggered and returns the new value
  /// returns Future<int>
  Future<int> nextVal([VoidCallback Function(int o)? nextval]) async {
    final val = await ExpensesDBModelSequenceManager()
        .sequence(SequenceIdentitySequence.getInstance, true);
    if (nextval != null) {
      nextval(val);
    }
    return val;
  }

  /// Get the current value
  /// returns Future<int>
  Future<int> currentVal([VoidCallback Function(int o)? currentval]) async {
    final val = await ExpensesDBModelSequenceManager()
        .sequence(SequenceIdentitySequence.getInstance, false);
    if (currentval != null) {
      currentval(val);
    }
    return val;
  }

  /// Reset sequence to start value
  /// returns start value
  Future<int> reset([VoidCallback Function(int o)? currentval]) async {
    final val = await ExpensesDBModelSequenceManager()
        .sequence(SequenceIdentitySequence.getInstance, false, reset: true);
    if (currentval != null) {
      currentval(val);
    }
    return val;
  }
}

/// End Region SEQUENCE IdentitySequence

class ExpensesDBModelSequenceManager extends SqfEntityProvider {
  ExpensesDBModelSequenceManager() : super(ExpensesDBModel());
}
// END OF ENTITIES
